### PR TITLE
[R] fix concat for symbol and NDArray. close #6650

### LINKED ISSUE #6650: [R] mx.nd.concat is expecting a MXNDArray instead of a list of MXNDArray
I think there might be a issue with the expected format of the `data` argument in `mx.nd.concat`. An error is returned if a list of MXNDArray is passed as argument mentionning:  

```
> x1 <- mx.nd.array(array(1:24, dim=c(4,6)))
> x2 <- mx.nd.array(array(1:24, dim=c(4,6)))
> x3 <- mx.nd.concat(data = c(x1, x2), num_args = 2, dim = 1)
Error in mx.nd.concat(data = c(x1, x2), num_args = 2, dim = 1) : 
  Expecting an external pointer: [type=list].
```

The equivalent code using `mx.symbol.concat` works fine.

### PR DESCRIPTION
**Pull request by thirdwing**
This needs more careful tests. I need to make sure I didn't break anything.

@jeremiedb

### CODE REVIEW

File: R-package/tests/testthat/test_ndarray.R [hunk 1]
```diff
@@ -48,3 +48,26 @@ test_that("ndarray ones, zeros, save and load", {
...
+  
+  x1 <- array(1:24, dim = c(4, 3, 2))
+  x2 <- array(25:48, dim = c(4, 3, 2))
+  x3 <- c(1:4, 25:28, 5:8, 29:32, 9:12, 33:36, 13:16, 37:40, 17:20, 41:44, 21:24, 45:48)
+  y1 <- mx.nd.array(x1)
+  y2 <- mx.nd.array(x2)
+  y3 <- mx.nd.concat(data = c(y1, y2), num_args = 2, dim = 2)
+  expect_equal(dim(y3), c(8, 3, 2))
+  expect_equal(as.array(y3), array(x3, dim = c(8, 3, 2)))
+})
```
Comment (thirdwing) [inline R-package/tests/testthat/test_ndarray.R]: @jeremiedb I also add some test for ndarray concat. It should fix the issue.
