### PR TITLE
Memory allocator bug fix #5035

### LINKED ISSUE #5035: High memory usage with bucketing
When using the bucketing module I'd expect the memory usage to be about the same as when using the normal module unrolled to the largest bucket size. However we observe unusually high GPU memory usage in MxNet when using multiple buckets. 
This can be reproduced/observed with the lstm_bucketing.py example from the latest MXNet commit as such:
in examples/rnn/lstm_bucketing.py change:

```
num-layers to 4
num-hidden to 1024
num-embed to 512
```

When using multiple buckets (see line 49), overall memory usage is 1419MB.
When changing line 49 to only use a single bucket (e.g. 60), overall memory usage is only 1185MB.

It should be noted that the initial memory usage for bucketing is the same (1185MB), but after a couple of batches the memory usage increases. We suspect this is due to the BucketingModule binding another sub module when a new bucket size is given by the data iterator and memory sharing across modules isn't working properly.

While for this model the difference is only 300 MB, we observed much higher differences in practice, making it difficult to train any reasonably sized model with bucketing.

Note: the default bucket key is of course the largest bucket.

### PR DESCRIPTION
**Pull request by eric-haibin-lin**
#4795
#5123
#5035 

(Together with NNVM PR https://github.com/dmlc/nnvm/pull/105) 

Found some inefficiency in the system and made a few changes related to memory allocation in MXNet: 

1.  In the bucketing module, `curr_module` is passed in as the `shared_module`, but instead the module with default_bucket_key should be passed. [Link](https://github.com/eric-haibin-lin/mxnet/blob/memory/python/mxnet/module/bucketing_module.py#L214).  
2.  When the memory pool of the default bucket module doesn't hold sufficient memory for other bucket to bind, extra NDArrays are allocated. But these NDArrays are not added back to the pool.  [Link](https://github.com/eric-haibin-lin/mxnet/blob/memory/src/executor/graph_executor.cc#L517)
3.  While matching new memory required to the existing memory slots in the pool, the new memory list is not sorted based on size, which could result in small memory blocks occupying a big one. 
4. The `NNVM_EXEC_MATCH_RANGE` variable has impact on the result of memory planning. Instead of letting the user to choose it, the backend could just try different values and choose the best one to automate the process. Some users are not even aware of this variable. [Link](https://github.com/eric-haibin-lin/nnvm/blob/memory/src/pass/plan_memory.cc#L299)

Fixing 1 and 2 reduce the memory quite a lot, while 3 and 4 bring marginal reduction if 1 and 2 are fixed (5% ~ 10%). 

Benchmark result on LSTM workload: 

| Version ( | 22673b6 (baseline) | 1 | 1 + 2 | 1 + 2 + 3 | 1 + 2 + 3 + 4 |
| --- | --- | --- | --- | --- | --- | 
| Memory (MB) | > 12288 (Out of Memory) | 4297 | 1956 | 1774 | 1718

Benchmark result on Neural Style workload 

| Version ( | 22673b6 (baseline) | 1 + 2 + 3 + 4 |
| --- | --- | --- | 
| Memory (MB) | > 12288 (Out of Memory) | 2034 |

* LSTM configuration:  python lstm_bucketing.py --gpus=0 --num-layers=4 --num-hidden=1024 --num-embed=512 --num-epochs=1
* Neural style uses default configuration

### CODE REVIEW

File: src/executor/graph_executor.cc [hunk 1]
```diff
@@ -321,16 +321,24 @@ void GraphExecutor::Init(nnvm::Symbol symbol,
                          const std::vector<OpReqType>& grad_req_type,
                          const std::vector<NDArray>& aux_states,
                          Executor* shared_exec) {
+  std::vector<SharedStorageEntry> shared_pool;
+  if (shared_exec != nullptr) {
+     for (auto& nd : dynamic_cast<GraphExecutor*>(shared_exec)->data_pool_) {
+       size_t bytes = nd.shape().Size() * mshadow::mshadow_sizeof(nd.dtype());
+       shared_pool.emplace_back(nd.ctx().dev_id, bytes);
```
Comment (piiswrong) [inline src/executor/graph_executor.cc]: Is this the same structure that was removed during nnvm refactor?

Comment (eric-haibin-lin) [inline src/executor/graph_executor.cc]: There used to be a struct like this

https://github.com/dmlc/mxnet/blob/v0.8.0/src/symbol/graph_executor.h#L60
https://github.com/dmlc/mxnet/blob/v0.8.0/src/symbol/graph_executor.h#L60

**Comment by piiswrong** [comment]
Could you add a memory test using bucketing module?

File: python/mxnet/module/base_module.py [hunk 2]
```diff
@@ -133,6 +133,7 @@ def __init__(self, logger=logging):
         self.params_initialized = False
         self.optimizer_initialized = False
         self._symbol = None
+        self.total_exec_bytes = 0
```
Comment (piiswrong) [inline python/mxnet/module/base_module.py]: Change to _total_exec_bytes to indicate users should not rely on this.

File: python/mxnet/module/executor_group.py [hunk 3]
```diff
@@ -558,6 +559,8 @@ def _get_or_reshape(name, shared_data_arrays, arg_shape, arg_type, context, logg
         executor = self.symbol.bind(ctx=context, args=arg_arrays,
                                     args_grad=grad_arrays, aux_states=aux_arrays,
                                     grad_req=self.grad_req, shared_exec=shared_exec)
+        # Get the total bytes allocated for this executor
+        self.total_exec_bytes += int(executor.debug_str().split('\n')[-3].split()[1])
```
Comment (piiswrong) [inline python/mxnet/module/executor_group.py]: Does this discount memory shared from previous exec?

**Comment by piiswrong** [comment]
nnvm pr is merged. Please update submodule

File: python/mxnet/module/executor_group.py (hunk 3 above)
Comment (eric-haibin-lin) [inline python/mxnet/module/executor_group.py]: No, it doesn't. But we definitely can add finer grained profiling stat later (how much extra memory allocated despite shared exec, how it's mapped to ops, which device does it live on, etc)

**Comment by eric-haibin-lin** [comment]
@piiswrong test passed. Please merge. Thanks!
